<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CmarMeetingBundleEntityLog_TotalProxy extends \Cmar\MeetingBundle\Entity\Log_Total implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDatetime($datetime)
    {
        $this->__load();
        return parent::setDatetime($datetime);
    }

    public function getDatetime()
    {
        $this->__load();
        return parent::getDatetime();
    }

    public function setParticipants($participants)
    {
        $this->__load();
        return parent::setParticipants($participants);
    }

    public function getParticipants()
    {
        $this->__load();
        return parent::getParticipants();
    }

    public function setActiveRooms($activeRooms)
    {
        $this->__load();
        return parent::setActiveRooms($activeRooms);
    }

    public function getActiveRooms()
    {
        $this->__load();
        return parent::getActiveRooms();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'datetime', 'participants', 'active_rooms');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}