<?php

namespace Cmar\MeetingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneUserByEmail($email)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT u FROM CmarMeetingBundle:User u                                                                                                                                                                          
                           WHERE u.email = :email")
            ->setParameter('email', $email)
            ->getSingleResult();

    }

    public function findUsersByTerm($term)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT u FROM CmarMeetingBundle:User u 
                           WHERE u.name LIKE :term
                           OR u.surname LIKE :term
                           OR u.email LIKE :term")
            ->setParameter('term', '%' . $term . '%')
            ->getResult();

    }

}