<?php

namespace Cmar\MeetingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NickNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NickNameRepository extends EntityRepository
{
    public function findOneNickNameByUserAndMeeting(User $user, Meeting $meeting)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT u FROM CmarMeetingBundle:NickName u 
                           WHERE u.user = :user
                           AND u.meeting = :meeting")
            ->setParameter('user', $user)
            ->setParameter('meeting', $meeting)
            ->getSingleResult();

    }

    public function findNickNameByUserOrderByRank(User $user)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT m FROM CmarMeetingBundle:Meeting m
                           LEFT JOIN m.nicknames n
                           WHERE n.user = :user
                           ORDER BY n.rank DESC")
            ->setParameter('user', $user)
            ->getResult();

    }

}



/*

            ->createQuery("SELECT u FROM CmarMeetingBundle:NickName u 
                           LEFT JOIN u.meeting m
                           WHERE u.user = :user
                           ORDER BY u.rank DESC")

*/